// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yakaboo;

#nullable disable

namespace Yakaboo.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231029115455_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yakaboo.Models.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("FirstName");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar")
                        .HasColumnName("LastName");

                    b.HasKey("ID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Stephen Robert",
                            Surname = "Covey"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Napoleon",
                            Surname = "Hill"
                        });
                });

            modelBuilder.Entity("Yakaboo.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AuthorID")
                        .HasColumnType("int")
                        .HasColumnName("AuthorId");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("PublisherID")
                        .HasColumnType("int")
                        .HasColumnName("PublisherId");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("Pages");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AuthorID = 1,
                            Price = 260.0,
                            PublisherID = 1,
                            Size = 356,
                            Title = "The 7 habits of highly effective people"
                        },
                        new
                        {
                            ID = 2,
                            AuthorID = 2,
                            Price = 237.0,
                            PublisherID = 1,
                            Size = 225,
                            Title = "Think and grow reach"
                        });
                });

            modelBuilder.Entity("Yakaboo.Models.Publisher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("ID");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Some1",
                            Name = "KSD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
